### ISSUE TITLE
URL in description and README broken

### ISSUE THREAD

**Issue by error505** [gh-non-developer-training-amplifon/github-games-VascoMoita#2]
The URL in the repository description and README are pointing to gh-non-developer-training-amplifon's copy of the game instead of yours.

Please fix both, so they point to your copy of the game at https://gh-non-developer-training-amplifon.github.io/github-games-VascoMoita.

**Comment by VascoMoita** [comment]
We have updated the link.
It is now working.
Kind Regards,
